# Generated by Django 4.2.24 on 2025-09-11 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='股票代號, e.g., AAPL', max_length=10, unique=True)),
                ('name', models.CharField(blank=True, help_text='公司名稱', max_length=100, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, help_text='最新成交價', max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最後更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('target_price', models.DecimalField(decimal_places=4, help_text='目標價格', max_digits=12)),
                ('condition', models.CharField(choices=[('GTE', '>='), ('LTE', '<=')], help_text='觸發條件 (GTE: 大於等於, LTE: 小於等於)', max_length=3)),
                ('status', models.CharField(choices=[('A', 'Active'), ('T', 'Triggered'), ('C', 'Cancelled')], default='A', help_text='警報狀態', max_length=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='關聯物件的 ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='持有數量/合約數', max_digits=12)),
                ('cost_basis', models.DecimalField(decimal_places=4, help_text='平均持有成本（每股/每合約）', max_digits=12)),
                ('content_type', models.ForeignKey(help_text='關聯的內容類型 (Stock或Option)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike_price', models.DecimalField(decimal_places=4, help_text='履約價', max_digits=12)),
                ('expiration_date', models.DateField(help_text='到期日')),
                ('option_type', models.CharField(choices=[('C', 'Call'), ('P', 'Put')], help_text='期權類型', max_length=1)),
                ('occ_symbol', models.CharField(blank=True, help_text='期權合約代號', max_length=30, null=True, unique=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, help_text='最新成交價', max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最後更新時間')),
                ('underlying_stock', models.ForeignKey(help_text='標的股票', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='portfolio_tracker.stock')),
            ],
            options={
                'ordering': ['expiration_date', 'strike_price'],
                'unique_together': {('underlying_stock', 'strike_price', 'expiration_date', 'option_type')},
            },
        ),
    ]
