# Generated by Django 4.2.24 on 2025-09-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='previous_close',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='昨日收盤價', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='previous_close',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='昨日收盤價', max_digits=12, null=True),
        ),
    ]
