# Generated by Django 4.2.24 on 2025-10-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_tracker', '0002_option_previous_close_stock_previous_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_value', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='PriceAlert',
        ),
    ]
