# Generated by Django 4.2.24 on 2025-10-08 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_tracker', '0004_deposit_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealizedGain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=100)),
                ('realized_pnl', models.DecimalField(decimal_places=2, help_text='Profit or Loss from a sell transaction', max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
