# k8s/celery-beat-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat-deployment
spec:
  replicas: 1 # 【重要】Beat 的副本數永遠只能是 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat-container
          image: portfolio-tracker:v1
          imagePullPolicy: Never
          # 啟動 Beat 的指令
          command: ["celery", "-A", "config", "beat", "-l", "info", "-S", "django"]
          envFrom:
            - secretRef:
                name: portfolio-secrets